version: '3.8'

services:
  snowflake:
    image: snowflake/snowflake
    environment:
      - SNOWFLAKE_ACCOUNT=<your_snowflake_account>
      - SNOWFLAKE_USER=<your_snowflake_user>
      - SNOWFLAKE_PASSWORD=<your_snowflake_password>
      - SNOWFLAKE_WAREHOUSE=<your_snowflake_warehouse>
      - SNOWFLAKE_DATABASE=<your_snowflake_database>
      - SNOWFLAKE_SCHEMA=<your_snowflake_schema>

  airflow:
    image: puckel/docker-airflow:latest
    restart: always
    depends_on:
      - snowflake
    environment:
      - LOAD_EX=n
      - EXECUTOR=LocalExecutor
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/requirements.txt:/requirements.txt
    entrypoint: /bin/bash -c "pip install -r /requirements.txt && airflow initdb && airflow webserver"
    ports:
      - "8080:8080"
    command: webserver

  airflow_scheduler:
    image: puckel/docker-airflow:latest
    restart: always
    depends_on:
      - airflow
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/requirements.txt:/requirements.txt
    entrypoint: /bin/bash -c "pip install -r /requirements.txt && airflow scheduler"
  
  dbt:
    image: fishtownanalytics/dbt:latest
    environment:
      - DBT_PROFILES_DIR=/root/.dbt
    volumes:
      - ./dbt:/usr/app/dbt
